changelog:
  exclude: {}
  categories:
    - title: '📦 Changes'
      labels:
        - '*'
      exclude:
        labels:
          - 'bug :bug:'
          - 'bug 🐛'
          - 'dependency :robot:'
          - 'dependency 🤖'
          - 'github-action :robot:'
          - 'github-action 🤖'

    - title: '🐛 Bug Fixes'
      labels:
        - 'bug :bug:'
        - 'bug 🐛'

    - title: '🆙 Dependencies'
      labels:
        - 'dependency :robot:'
        - 'dependency 🤖'
        - 'github-action :robot:'
        - 'github-action 🤖'
