changelog:
  exclude: {}
  categories:
    - title: 'Features 🚀'
      labels:
        - 'feature-request :construction:'
        - 'feature-request 🚧'

    - title: 'Bug Fixes 🐛'
      labels:
        - 'bug :bug:'
        - 'bug 🐛'

    - title: 'Changes 📦'
      labels:
        - '*'
      exclude:
        labels:
          - 'feature-request :construction:'
          - 'feature-request 🚧'
          - 'bug :bug:'
          - 'bug 🐛'
          - 'dependency :robot:'
          - 'dependency 🤖'
          - 'github-action :robot:'
          - 'github-action 🤖'

    - title: 'Dependency Updates 🆙'
      labels:
        - 'dependency :robot:'
        - 'dependency 🤖'
        - 'github-action :robot:'
        - 'github-action 🤖'
