version: 2

project_name: gh_report

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
        goarm: "7"

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum

snapshot:
  version_template: "{{ incpatch .Version }}"

changelog:
  use: github-native

release:
  prerelease: auto
