project_name: gh_report

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format: binary

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}"

changelog:
  use: github-native

release:
  prerelease: auto
