blank_issues_enabled: false

contact_links:
  - name: Twitter
    url: https://twitter.com/_stoe
    about: Find me on Twitter.
  - name: LinkedIn
    url: https://www.linkedin.com/in/stoe
    about: Find me on LinkedIn.
